### ISSUE TITLE
Probable port to avs??

### ISSUE THREAD

**Issue by kedaitinh12** [AmusementClub/VapourSynth-EEDI2CUDA#3]
Please can you port to avisynth too???
you can make the plugin work in both https://github.com/HomeOfAviSynthPlusEvolution/neo_DFTTest (this is backport of vs DFTTest and now it's work on both)

**Comment by misakikasumi** [comment]
Any interest? @AkarinVS 
PS: write your D_CIDE script first

**Comment by kedaitinh12** [comment]
Sr, i'm noob. What mean D_CIDE script???

**Comment by AkarinVS** [comment]
Sorry, there is already too much on my plate.
Perhaps @asd-g could help.

>

**Comment by kedaitinh12** [comment]
But Asd-g won't support CUDA or any other related GPU. Thanks for reply

**Comment by misakikasumi** [comment]
Oh, this shouldn’t be closed.

**Comment by misakikasumi** [comment]
Perhaps I can look into it, or wait until Akarin has time, or something else could help. But no schedule or milestone for now.

**Comment by kedaitinh12** [comment]
Oh, thanks. Just do when you freetime

**Comment by WolframRhodium** [comment]
I will port it this weekend.

**Comment by kedaitinh12** [comment]
Thanks, you're my hero

Vào Thứ Tư, 11 tháng 8, 2021, WolframRhodium ***@***.***> đã
viết:

**Comment by Asd-g** [comment]
> 
> 
> But Asd-g won't support CUDA or any other related GPU. Thanks for reply

@kedaitinh12, I don't have NVIDIA GPU - cannot test, debug and etc. I cannot help with anything CUDA related.

**Comment by kedaitinh12** [comment]
> > But Asd-g won't support CUDA or any other related GPU. Thanks for reply
> 
> @kedaitinh12, I don't have NVIDIA GPU - cannot test, debug and etc. I cannot help with anything CUDA related.

I knew it

**Comment by WolframRhodium** [comment]
Ported in https://github.com/AmusementClub/VapourSynth-EEDI2CUDA/commit/dec6f26bd31b2eb3e603d554252f124acf48bb1e. Please check the binary in [Actions](https://github.com/AmusementClub/VapourSynth-EEDI2CUDA/actions).

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
But can you add x86 ver same BM3DCUDA???

**Comment by misakikasumi** [comment]
I personally don't think x86 build is necessary. But feel free to build it by yourself. [Instruction](https://github.com/AmusementClub/VapourSynth-EEDI2CUDA/blob/AVS%2B/.github/workflows/build.yml)

**Comment by WolframRhodium** [comment]
Done with https://github.com/AmusementClub/VapourSynth-EEDI2CUDA/commit/2b351133036cd5b0ec75c957a1b8bce5663f8e58.

**Comment by kedaitinh12** [comment]
Thanks
